CREATE TABLE IF NOT EXISTS `group` (
  `GroupID` int(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  `Active` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;