CREATE TABLE IF NOT EXISTS `@prefixgroupright` (
  `GroupRightID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `GroupID` int(10) NOT NULL,
  `RightID` int(20) NOT NULL,
  `TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Active` int(11) NOT NULL DEFAULT '1',
  FOREIGN KEY (`GroupID`) REFERENCES `@prefixgroup`(`GroupID`) ON DELETE CASCADE,
  FOREIGN KEY (`RightID`) REFERENCES `@prefixright`(`RightID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
