CREATE TABLE IF NOT EXISTS `structurefield` (
  `StructureFieldID` int(11) NOT NULL PRIMARY KEY,
  `StructureID` int(11) NOT NULL,
  `FieldID` int(11) NOT NULL,
  `Modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Active` int(11) NOT NULL,
  FOREIGN KEY (`FieldID`) REFERENCES `field`(`FieldID`) ON DELETE CASCADE,
  FOREIGN KEY (`StructureID`) REFERENCES `structure`(`StructureID`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;