CREATE TABLE IF NOT EXISTS `@prefixstructure` (
  `StructureID` int(11) NOT NULL PRIMARY KEY,
  `ParentID` int(11) NOT NULL,
  `Name` varchar(255) NOT NULL,
  `locale` varchar(10) NOT NULL,
  `Created` datetime NOT NULL,
  `UserID` int(11) NOT NULL,
  `Modyfied` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Url` varchar(255) NOT NULL,
  `MaterialID` int(11) NOT NULL,
  `PriorityNumber` int(11) NOT NULL,
  `type` int(1) NOT NULL DEFAULT '0',
  `Active` int(11) NOT NULL DEFAULT '1',
  `system` int(1) NOT NULL DEFAULT '0',
  `hidden` int(1) NOT NULL DEFAULT '0',
  FOREIGN KEY (MaterialID) REFERENCES @prefixmaterial(MaterialID),
  FOREIGN KEY (ParentID) REFERENCES @prefixstructure(StructureID),
  FOREIGN KEY (UserID) REFERENCES @prefixuser(UserID),
  ADD KEY `Url` (`Url`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;